In [1]:
import pandas as pd

In [2]:
# 1. CARGA DE DATOS
# Cargamos los datos limpios que exportamos en el EDA
df_detalle = pd.read_csv(r'C:\Users\nata_\Documents\MLOps\Introduction_to_MLOps\proyecto_2\Combos_Tostao\data\datos_tostao_limpios.csv')

# Convertimos la fecha a tipo datetime para que mantenga sus propiedades organizadas
df_detalle['fecha'] = pd.to_datetime(df_detalle['fecha'])

print(f"¡Datos cargados correctamente en el nuevo Notebook! Total de registros: {len(df_detalle)}")
df_detalle.head()

¡Datos cargados correctamente en el nuevo Notebook! Total de registros: 18376

,id_ticket,id_producto,cantidad,precio_unitario,nombre,categoria,subcategoria,fecha,id_tienda,id_cliente,venta_total,mes,dia_semana
0,TICKET_000001,PROD_030,1,4500,Torta de Zanahoria,Alimentos,Panadería Dulce,2024-08-29,TOSTAO_15,CUST_01364,4500,August,Thursday
1,TICKET_000002,PROD_006,1,2500,Aromática,Bebidas,Calientes,2024-02-04,TOSTAO_18,CUST_01956,2500,February,Sunday
2,TICKET_000003,PROD_033,1,1500,Chocolatina,Alimentos,Panadería Dulce,2024-02-23,TOSTAO_18,CUST_01501,1500,February,Friday
3,TICKET_000003,PROD_021,1,3500,Pastel de Pollo,Alimentos,Panadería Sal,2024-02-23,TOSTAO_18,CUST_01501,3500,February,Friday
4,TICKET_000004,PROD_019,1,3200,Empanada de Carne,Alimentos,Panadería Sal,2024-10-30,TOSTAO_08,CUST_01276,3200,October,Wednesday

In [3]:

# 1. Aseguramos el orden cronológico absoluto de las transacciones
df_ordenado = df_detalle.sort_values(by='fecha').reset_index(drop=True)

# 2. Calculamos la posición exacta para el corte del 80%
punto_corte = int(len(df_ordenado) * 0.80)
fecha_corte = df_ordenado.iloc[punto_corte]['fecha']

# 3. Dividimos el conjunto de datos
df_train_raw = df_ordenado.iloc[:punto_corte].copy()
df_test_raw = df_ordenado.iloc[punto_corte:].copy()

# 4. Métricas para auditar la división
total_filas = len(df_ordenado)
filas_train = len(df_train_raw)
filas_test = len(df_test_raw)

print("==================================================================")
print("🔍 AUDITORÍA PASO 1: DIVISIÓN TEMPORAL CRONOLÓGICA")
print("==================================================================")
print(f"📦 Dataset Completo    : {total_filas:,} filas de transacciones")
print(f"📅 Fecha de Corte      : {fecha_corte}")
print("-" * 66)
print(f"🟢 Entrenamiento (Train): {filas_train:,} filas ({filas_train/total_filas:.1%})")
print(f"   • Rango de fechas   : Desde {df_train_raw['fecha'].min().strftime('%Y-%m-%d')} hasta {df_train_raw['fecha'].max().strftime('%Y-%m-%d')}")
print("-" * 66)
print(f"🔵 Validación (Test)   : {filas_test:,} filas ({filas_test/total_filas:.1%})")
print(f"   • Rango de fechas   : Desde {df_test_raw['fecha'].min().strftime('%Y-%m-%d')} hasta {df_test_raw['fecha'].max().strftime('%Y-%m-%d')}")
print("==================================================================")

==================================================================
🔍 AUDITORÍA PASO 1: DIVISIÓN TEMPORAL CRONOLÓGICA
==================================================================
📦 Dataset Completo    : 18,376 filas de transacciones
📅 Fecha de Corte      : 2024-10-17 00:00:00
------------------------------------------------------------------
🟢 Entrenamiento (Train): 14,700 filas (80.0%)
   • Rango de fechas   : Desde 2024-01-01 hasta 2024-10-17
------------------------------------------------------------------
🔵 Validación (Test)   : 3,676 filas (20.0%)
   • Rango de fechas   : Desde 2024-10-17 hasta 2024-12-30
==================================================================

In [4]:
# Preparación de Datos (One-Hot Encoding)

def aplicar_one_hot_encoding(df_insumo: pd.DataFrame) -> pd.DataFrame:
    """
    Transforma el formato transaccional a una estructura matricial
    donde las columnas son los productos y las celdas indican si el
    producto fue comprado (1) o no (0) en cada ticket.
    """
    # 1. Agrupamos por ticket y producto sumando cantidades
    matriz_pivot = df_insumo.groupby(['id_ticket', 'nombre'])['cantidad'].sum().unstack().reset_index().fillna(0)
    
    # 2. Establecemos el id_ticket como índice de la matriz
    matriz_pivot.set_index('id_ticket', inplace=True)
    
    # 3. Codificación binaria: Si la cantidad es mayor a 0 se asigna 1, si no 0
    matriz_binaria = matriz_pivot.map(lambda x: 1 if x > 0 else 0)
    
    return matriz_binaria

print("==================================================================")
print("⚙️  EJECUTANDO PASO 2: ONE-HOT ENCODING MULTI-DATASET")
print("==================================================================")

# Aplicamos la transformación de canasta a Train y Test por separado
basket_train = aplicar_one_hot_encoding(df_train_raw)
basket_test = aplicar_one_hot_encoding(df_test_raw)

print(f"🟢 Dimensiones de la matriz de Train : {basket_train.shape[0]} tickets x {basket_train.shape[1]} productos")
print(f"🔵 Dimensiones de la matriz de Test  : {basket_test.shape[0]} tickets x {basket_test.shape[1]} productos")
print("------------------------------------------------------------------")

==================================================================
⚙️  EJECUTANDO PASO 2: ONE-HOT ENCODING MULTI-DATASET
==================================================================
🟢 Dimensiones de la matriz de Train : 7991 tickets x 35 productos
🔵 Dimensiones de la matriz de Test  : 2010 tickets x 35 productos
------------------------------------------------------------------

In [5]:
import os

print("==================================================================")
print("EJECUTANDO PASO 3: EXPORTACIÓN DE MATRICES (REPRODUCIBILIDAD)")
print("==================================================================")

# Exportar las matrices binarias (One-Hot Encoded) a formato CSV
basket_train.to_csv('train_basket.csv')
basket_test.to_csv('test_basket.csv')

print("🟢 Archivo guardado de manera exitosa: 'train_basket.csv'")
print("🔵 Archivo guardado de manera exitosa: 'test_basket.csv'")
print("------------------------------------------------------------------")

==================================================================
EJECUTANDO PASO 3: EXPORTACIÓN DE MATRICES (REPRODUCIBILIDAD)
==================================================================
🟢 Archivo guardado de manera exitosa: 'train_basket.csv'
🔵 Archivo guardado de manera exitosa: 'test_basket.csv'
------------------------------------------------------------------

In [8]:
import sys
!{sys.executable} -m pip install mlflow

Collecting mlflow
  Using cached mlflow-3.12.0-py3-none-any.whl.metadata (49 kB)
Collecting mlflow-skinny==3.12.0 (from mlflow)
  Using cached mlflow_skinny-3.12.0-py3-none-any.whl.metadata (50 kB)
Collecting mlflow-tracing==3.12.0 (from mlflow)
  Using cached mlflow_tracing-3.12.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting Flask<4 (from mlflow)
  Using cached flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting aiohttp<4 (from mlflow)
  Downloading aiohttp-3.13.5-cp310-cp310-win_amd64.whl.metadata (8.4 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Using cached alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Downloading cryptography-46.0.7-cp38-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Using cached huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow) (3.10.8)
Requirement already satisfied: numpy<3 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow) (2.3.3)
Collecting pyarrow<24,>=4.0.0 (from mlflow)
  Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: scikit-learn<2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow) (1.7.2)
Requirement already satisfied: scipy<2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow) (1.15.3)
Collecting skops<1 (from mlflow)
  Using cached skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached cachetools-7.1.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (8.3.1)
Collecting cloudpickle<4 (from mlflow-skinny==3.12.0->mlflow)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached databricks_sdk-0.110.0-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: fastapi<1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.135.1)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.12.0->mlflow)
  Using cached gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Collecting importlib_metadata!=4.7.0,<10,>=3.7.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_api-1.42.1-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_proto-1.42.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_sdk-1.42.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: packaging<27 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (25.0)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached protobuf-7.35.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (2.12.5)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: starlette<1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlflow-skinny==3.12.0->mlflow) (0.41.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4->mlflow)
  Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4->mlflow)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting async-timeout<6.0,>=4.0 (from aiohttp<4->mlflow)
  Downloading async_timeout-5.0.1-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from aiohttp<4->mlflow) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4->mlflow)
  Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4->mlflow)
  Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4->mlflow)
  Downloading propcache-0.5.2-cp310-cp310-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4->mlflow)
  Downloading yarl-1.24.2-cp310-cp310-win_amd64.whl.metadata (97 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Using cached mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: tomli in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (2.4.0)
Requirement already satisfied: colorama in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.12.0->mlflow) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached google_auth-2.53.0-py3-none-any.whl.metadata (5.5 kB)
Collecting protobuf<8,>=3.12.0 (from mlflow-skinny==3.12.0->mlflow)
  Using cached protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pywin32>=304 (from docker<8,>=4.0.0->mlflow)
  Downloading pywin32-311-cp310-cp310-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.6.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from fastapi<1->mlflow-skinny==3.12.0->mlflow) (0.0.4)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Using cached werkzeug-3.1.8-py3-none-any.whl.metadata (4.0 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.12.0->mlflow)
  Using cached smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.12.0->mlflow)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib<4->mlflow) (3.3.2)
Collecting opentelemetry-semantic-conventions==0.63b1 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.12.0->mlflow)
  Using cached opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pandas<3->mlflow) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.12.0->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.12.0->mlflow) (2026.2.25)
Requirement already satisfied: joblib>=1.2.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.5.1-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from starlette<1->mlflow-skinny==3.12.0->mlflow) (4.12.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from anyio<5,>=3.6.2->starlette<1->mlflow-skinny==3.12.0->mlflow) (1.3.1)
Requirement already satisfied: h11>=0.8 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from uvicorn<1->mlflow-skinny==3.12.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: wcwidth in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.12.0->mlflow)
  Using cached pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Using cached mlflow-3.12.0-py3-none-any.whl (10.6 MB)
Using cached mlflow_skinny-3.12.0-py3-none-any.whl (3.3 MB)
Using cached mlflow_tracing-3.12.0-py3-none-any.whl (1.6 MB)
Downloading aiohttp-3.13.5-cp310-cp310-win_amd64.whl (462 kB)
Using cached alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Using cached cachetools-7.1.3-py3-none-any.whl (16 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-46.0.7-cp38-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.5 MB 2.4 MB/s eta 0:00:02
   ------------ --------------------------- 1.0/3.5 MB 2.3 MB/s eta 0:00:02
   ------------------------ --------------- 2.1/3.5 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 3.9 MB/s  0:00:01
Using cached databricks_sdk-0.110.0-py3-none-any.whl (892 kB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached flask-3.1.3-py3-none-any.whl (103 kB)
Using cached flask_cors-6.0.2-py3-none-any.whl (13 kB)
Using cached gitpython-3.1.50-py3-none-any.whl (212 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached google_auth-2.53.0-py3-none-any.whl (246 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_core-3.2.8-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached huey-2.6.0-py3-none-any.whl (76 kB)
Using cached importlib_metadata-9.0.0-py3-none-any.whl (27 kB)
Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl (46 kB)
Using cached opentelemetry_api-1.42.1-py3-none-any.whl (61 kB)
Using cached opentelemetry_proto-1.42.1-py3-none-any.whl (71 kB)
Using cached opentelemetry_sdk-1.42.1-py3-none-any.whl (170 kB)
Using cached opentelemetry_semantic_conventions-0.63b1-py3-none-any.whl (203 kB)
Using cached protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   - -------------------------------------- 1.3/27.5 MB 6.7 MB/s eta 0:00:04
   ---- ----------------------------------- 2.9/27.5 MB 6.5 MB/s eta 0:00:04

  WARNING: The scripts pywin32_postinstall.exe and pywin32_testall.exe are installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script huey_consumer.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script waitress-serve.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script sqlformat.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dotenv.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mako-render.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script alembic.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mlflow.exe is installed in 'c:\Users\nata_\anaconda3\envs\my_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

   ------ --------------------------------- 4.5/27.5 MB 6.6 MB/s eta 0:00:04
   --------- ------------------------------ 6.8/27.5 MB 7.2 MB/s eta 0:00:03
   ------------ --------------------------- 8.7/27.5 MB 7.4 MB/s eta 0:00:03
   ---------------- ----------------------- 11.3/27.5 MB 7.4 MB/s eta 0:00:03
   ------------------ --------------------- 12.6/27.5 MB 7.0 MB/s eta 0:00:03
   -------------------- ------------------- 14.4/27.5 MB 7.0 MB/s eta 0:00:02
   ----------------------- ---------------- 16.0/27.5 MB 6.9 MB/s eta 0:00:02
   --------------------------- ------------ 18.6/27.5 MB 7.1 MB/s eta 0:00:02
   ----------------------------- ---------- 20.2/27.5 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 22.0/27.5 MB 7.2 MB/s eta 0:00:01
   ---------------------------------- ----- 23.9/27.5 MB 7.3 MB/s eta 0:00:01
   ------------------------------------ --- 24.9/27.5 MB 7.3 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/27.5 MB 6.9 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/27.5 MB 6.9 MB/s eta 0:00:01
   ------------------------------------ --- 25.4/27.5 MB 6.9 MB/s eta 0:00:01
   ------------------------------------- -- 25.7/27.5 MB 6.0 MB/s eta 0:00:01
   ------------------------------------- -- 26.0/27.5 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 26.7/27.5 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 4.8 MB/s  0:00:05
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached skops-0.14.0-py3-none-any.whl (132 kB)
Using cached smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading sqlalchemy-2.0.49-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.2 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.2 MB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.1 MB 1.3 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.6 MB/s  0:00:01
Using cached sqlparse-0.5.5-py3-none-any.whl (46 kB)
Using cached waitress-3.0.2-py3-none-any.whl (56 kB)
Downloading yarl-1.24.2-cp310-cp310-win_amd64.whl (92 kB)
Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
Downloading greenlet-3.5.1-cp310-cp310-win_amd64.whl (237 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading propcache-0.5.2-cp310-cp310-win_amd64.whl (42 kB)
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Using cached pyasn1-0.6.3-py3-none-any.whl (83 kB)
Downloading pywin32-311-cp310-cp310-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 621.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.6 MB 1.2 MB/s eta 0:00:08
   ------ --------------------------------- 1.6/9.6 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.6 MB 1.8 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.6 MB 1.8 MB/s eta 0:00:04
   ------------- -------------------------- 3.1/9.6 MB 1.7 MB/s eta 0:00:04
   -------------- ------------------------- 3.4/9.6 MB 1.8 MB/s eta 0:00:04
   --------------- ------------------------ 3.7/9.6 MB 1.6 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.6 MB 1.7 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.6 MB 1.8 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.6 MB 1.9 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.6 MB 1.9 MB/s eta 0:00:03
   ------------------------- -------------- 6.0/9.6 MB 1.8 MB/s eta 0:00:02
   -------------------------- ------------- 6.3/9.6 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.6 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.6 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.6 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.6 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.6 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 1.9 MB/s  0:00:05
Using cached werkzeug-3.1.8-py3-none-any.whl (226 kB)
Using cached zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached mako-1.3.12-py3-none-any.whl (78 kB)
Installing collected packages: pywin32, huey, zipp, werkzeug, waitress, sqlparse, smmap, python-dotenv, pyasn1, pyarrow, protobuf, propcache, prettytable, opentelemetry-api, multidict, Mako, itsdangerous, greenlet, graphql-core, frozenlist, cloudpickle, cachetools, blinker, async-timeout, aiohappyeyeballs, yarl, sqlalchemy, pyasn1-modules, opentelemetry-semantic-conventions, opentelemetry-proto, importlib_metadata, graphql-relay, gitdb, Flask, docker, cryptography, aiosignal, skops, opentelemetry-sdk, graphene, google-auth, gitpython, Flask-CORS, alembic, aiohttp, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow

   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
   ----------------------------------------  0/49 [pywin32]
    ---------------------------------------  1/49 [huey]
    ---------------------------------------  1/49 [huey]
    ---------------------------------------  1/49 [huey]
   -- -------------------------------------  3/49 [werkzeug]
   -- -------------------------------------  3/49 [werkzeug]
   -- -------------------------------------  3/49 [werkzeug]
   --- ------------------------------------  4/49 [waitress]
   --- ------------------------------------  4/49 [waitress]
   ---- -----------------------------------  5/49 [sqlparse]
   ---- -----------------------------------  6/49 [smmap]
   ------ ---------------------------------  8/49 [pyasn1]
   ------ ---------------------------------  8/49 [pyasn1]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   ------- --------------------------------  9/49 [pyarrow]
   -------- ------------------------------- 10/49 [protobuf]
   -------- ------------------------------- 10/49 [protobuf]
   -------- ------------------------------- 10/49 [protobuf]
   -------- ------------------------------- 11/49 [propcache]
   --------- ------------------------------ 12/49 [prettytable]
   ---------- ----------------------------- 13/49 [opentelemetry-api]
   ---------- ----------------------------- 13/49 [opentelemetry-api]
   ------------ --------------------------- 15/49 [Mako]
   ------------ --------------------------- 15/49 [Mako]
   ------------- -------------------------- 17/49 [greenlet]
   ------------- -------------------------- 17/49 [greenlet]
   ------------- -------------------------- 17/49 [greenlet]
   -------------- ------------------------- 18/49 [graphql-core]
   -------------- ------------------------- 18/49 [graphql-core]
   -------------- ------------------------- 18/49 [graphql-core]
   -------------- ------------------------- 18/49 [graphql-core]
   -------------- ------------------------- 18/49 [graphql-core]
   --------------- ------------------------ 19/49 [frozenlist]
   ----------------- ---------------------- 22/49 [blinker]
   -------------------- ------------------- 25/49 [yarl]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   --------------------- ------------------ 26/49 [sqlalchemy]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ---------------------- ----------------- 27/49 [pyasn1-modules]
   ------------------ -------------- 28/49 [opentelemetry-semantic-conventions]
   ------------------ -------------- 28/49 [opentelemetry-semantic-conventions]
   ------------------ -------------- 28/49 [opentelemetry-semantic-conventions]
   ------------------ -------------- 28/49 [opentelemetry-semantic-conventions]
   ------------------ -------------- 28/49 [opentelemetry-semantic-conventions]
   ----------------------- ---------------- 29/49 [opentelemetry-proto]
   ----------------------- ---------------- 29/49 [opentelemetry-proto]
   ------------------------- -------------- 31/49 [graphql-relay]
   -------------------------- ------------- 32/49 [gitdb]
   -------------------------- ------------- 33/49 [Flask]
   -------------------------- ------------- 33/49 [Flask]
   --------------------------- ------------ 34/49 [docker]
   --------------------------- ------------ 34/49 [docker]
   --------------------------- ------------ 34/49 [docker]
   ---------------------------- ----------- 35/49 [cryptography]
   ---------------------------- ----------- 35/49 [cryptography]
   ---------------------------- ----------- 35/49 [cryptography]
   ---------------------------- ----------- 35/49 [cryptography]
   ---------------------------- ----------- 35/49 [cryptography]
   ------------------------------ --------- 37/49 [skops]
   ------------------------------ --------- 37/49 [skops]
   ------------------------------- -------- 38/49 [opentelemetry-sdk]
   ------------------------------- -------- 38/49 [opentelemetry-sdk]
   ------------------------------- -------- 38/49 [opentelemetry-sdk]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   ------------------------------- -------- 39/49 [graphene]
   -------------------------------- ------- 40/49 [google-auth]
   -------------------------------- ------- 40/49 [google-auth]
   -------------------------------- ------- 40/49 [google-auth]
   -------------------------------- ------- 40/49 [google-auth]
   --------------------------------- ------ 41/49 [gitpython]
   --------------------------------- ------ 41/49 [gitpython]
   ----------------------------------- ---- 43/49 [alembic]
   ----------------------------------- ---- 43/49 [alembic]
   ----------------------------------- ---- 43/49 [alembic]
   ----------------------------------- ---- 43/49 [alembic]
   ----------------------------------- ---- 43/49 [alembic]
   ----------------------------------- ---- 44/49 [aiohttp]
   ----------------------------------- ---- 44/49 [aiohttp]
   ----------------------------------- ---- 44/49 [aiohttp]
   ----------------------------------- ---- 44/49 [aiohttp]
   ----------------------------------- ---- 44/49 [aiohttp]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------ --- 45/49 [databricks-sdk]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   ------------------------------------- -- 46/49 [mlflow-tracing]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]
   -------------------------------------- - 47/49 [mlflow-skinny]

In [10]:
import sys
!{sys.executable} -m pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (2.2.6)
Requirement already satisfied: pandas>=0.24.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=0.13.2 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pandas>=0.24.2->mlxtend) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\nata_\anaconda3\envs\my_env\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [12]:
import mlflow

print("==================================================================")
print("CONFIGURACIÓN DE MLFLOW")
print("==================================================================")

# Definimos la ruta absoluta directa a la raíz del proyecto (fuera de notebooks)
MLRUNS_DIR = r"C:\Users\nata_\Documents\MLOps\Introduction_to_MLOps\proyecto_2\Combos_Tostao\mlruns"

# Configuración de URI y Experimento
mlflow.set_tracking_uri(f"file:///{MLRUNS_DIR}")
mlflow.set_experiment("Market_Basket_Tostao")

print("------------------------------------------------------------------")
print("✅ ¡Entorno de MLflow inicializado correctamente!")
print(f"📁 Tracking de experimentos activo en: {MLRUNS_DIR}")
print("==================================================================")

c:\Users\nata_\anaconda3\envs\my_env\lib\site-packages\mlflow\tracking\_tracking_service\utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
2026/05/21 16:04:07 INFO mlflow.tracking.fluent: Experiment with name 'Market_Basket_Tostao' does not exist. Creating a new experiment.

==================================================================
CONFIGURACIÓN DE MLFLOW
==================================================================
------------------------------------------------------------------
✅ ¡Entorno de MLflow inicializado correctamente!
📁 Tracking de experimentos activo en: C:\Users\nata_\Documents\MLOps\Introduction_to_MLOps\proyecto_2\Combos_Tostao\mlruns
==================================================================

In [13]:
from mlxtend.frequent_patterns import apriori, association_rules

with mlflow.start_run(run_name="Soporte_1%"):
    # 1. Parámetros
    mlflow.log_param("min_support", 0.01)
    mlflow.log_param("min_confidence", 0.10)
    
    # 2. Algoritmo
    frequent_train = apriori(basket_train, min_support=0.01, use_colnames=True)
    reglas_train = association_rules(frequent_train, metric="confidence", min_threshold=0.1)
    
    # 3. Métricas
    total_reglas_crudas = len(reglas_train)
    lift_maximo = reglas_train['lift'].max() if not reglas_train.empty else 0
    
    mlflow.log_metric("reglas_descubiertas_crudas", total_reglas_crudas)
    mlflow.log_metric("lift_maximo_train", lift_maximo)
    
    print("==================================================================")
    print("🚀 EXPERIMENTO 1 GUARDADO EN MLFLOW")
    print("==================================================================")
    print(f"📊 Parámetros: Soporte = 1%, Confianza = 10%")
    print(f"📈 Métricas Guardadas: {total_reglas_crudas} reglas crudas encontradas.")

==================================================================
🚀 EXPERIMENTO 1 GUARDADO EN MLFLOW
==================================================================
📊 Parámetros: Soporte = 1%, Confianza = 10%
📈 Métricas Guardadas: 18 reglas crudas encontradas.

c:\Users\nata_\anaconda3\envs\my_env\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [14]:
from mlxtend.frequent_patterns import apriori, association_rules

with mlflow.start_run(run_name="Soporte_Relajado_0.5%"):
    # 1. Parámetros
    mlflow.log_param("min_support", 0.005)
    mlflow.log_param("min_confidence", 0.10)
    
    # 2. Algoritmo
    frequent_train_exp = apriori(basket_train, min_support=0.005, use_colnames=True)
    reglas_train_exp = association_rules(frequent_train_exp, metric="confidence", min_threshold=0.1)
    
    # 3. Métricas
    total_reglas_exp = len(reglas_train_exp)
    lift_maximo_exp = reglas_train_exp['lift'].max() if not reglas_train_exp.empty else 0
    
    mlflow.log_metric("reglas_descubiertas_crudas", total_reglas_exp)
    mlflow.log_metric("lift_maximo_train", lift_maximo_exp)
    
    print("==================================================================")
    print("🧪 EXPERIMENTO 2 GUARDADO EN MLFLOW")
    print("==================================================================")
    print(f"📊 Parámetros: Soporte = 0.5%, Confianza = 10%")
    print(f"📈 Métricas Guardadas: {total_reglas_exp} reglas crudas encontradas.")

==================================================================
🧪 EXPERIMENTO 2 GUARDADO EN MLFLOW
==================================================================
📊 Parámetros: Soporte = 0.5%, Confianza = 10%
📈 Métricas Guardadas: 19 reglas crudas encontradas.

c:\Users\nata_\anaconda3\envs\my_env\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [15]:
from mlxtend.frequent_patterns import apriori, association_rules

with mlflow.start_run(run_name="Soporte_Ultra_Bajo_0.2%"):
    # 1. Registramos parámetros en MLflow
    mlflow.log_param("min_support", 0.002)     # Un umbral muy bajo
    mlflow.log_param("min_confidence", 0.10)   # Mantenemos la confianza para comparar
    
    # 2. Ejecutamos el algoritmo
    frequent_train_exp3 = apriori(basket_train, min_support=0.002, use_colnames=True)
    reglas_train_exp3 = association_rules(frequent_train_exp3, metric="confidence", min_threshold=0.1)
    
    # 3. Métricas para el análisis de sensibilidad
    total_reglas_exp3 = len(reglas_train_exp3)
    lift_maximo_exp3 = reglas_train_exp3['lift'].max() if not reglas_train_exp3.empty else 0
    
    mlflow.log_metric("reglas_descubiertas_crudas", total_reglas_exp3)
    mlflow.log_metric("lift_maximo_train", lift_maximo_exp3)
    
    print("==================================================================")
    print("🔬 EXPERIMENTO 3 GUARDADO EN MLFLOW")
    print("==================================================================")
    print(f"📊 Parámetros: Soporte = 0.2%, Confianza = 10%")
    print(f"📈 Métricas Guardadas: {total_reglas_exp3} reglas crudas encontradas.")

c:\Users\nata_\anaconda3\envs\my_env\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

==================================================================
🔬 EXPERIMENTO 3 GUARDADO EN MLFLOW
==================================================================
📊 Parámetros: Soporte = 0.2%, Confianza = 10%
📈 Métricas Guardadas: 52 reglas crudas encontradas.

In [16]:
from mlxtend.frequent_patterns import apriori, association_rules

with mlflow.start_run(run_name="Soporte_Extremo_0.1%"):
    # 1. Registramos el parámetro en MLflow
    mlflow.log_param("min_support", 0.001)     # El límite inferior absoluto
    mlflow.log_param("min_confidence", 0.10)   # Mantenemos la confianza fija
    
    # 2. Ejecutamos el algoritmo
    frequent_train_exp4 = apriori(basket_train, min_support=0.001, use_colnames=True)
    reglas_train_exp4 = association_rules(frequent_train_exp4, metric="confidence", min_threshold=0.1)
    
    # 3. Métricas
    total_reglas_exp4 = len(reglas_train_exp4)
    lift_maximo_exp4 = reglas_train_exp4['lift'].max() if not reglas_train_exp4.empty else 0
    
    mlflow.log_metric("reglas_descubiertas_crudas", total_reglas_exp4)
    mlflow.log_metric("lift_maximo_train", lift_maximo_exp4)
    
    print("==================================================================")
    print("💥 EXPERIMENTO 4 GUARDADO EN MLFLOW")
    print("==================================================================")
    print(f"📊 Parámetros: Soporte = 0.1%, Confianza = 10%")
    print(f"📈 Métricas Guardadas: {total_reglas_exp4} reglas crudas encontradas.")

c:\Users\nata_\anaconda3\envs\my_env\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

==================================================================
💥 EXPERIMENTO 4 GUARDADO EN MLFLOW
==================================================================
📊 Parámetros: Soporte = 0.1%, Confianza = 10%
📈 Métricas Guardadas: 257 reglas crudas encontradas.

In [18]:

# 1. Crear el diccionario con los datos limpios de los 4 experimentos
datos_experimentos = {
    "Soporte Mínimo": ["0.1%", "0.2%", "0.5%", "1.0%"],
    "Hiperparámetro (min_support)": [0.001, 0.002, 0.005, 0.010],
    "Reglas Descubiertas": [257, 52, 19, 18],
    "Lift Máximo": [13.770, 10.140, 8.293, 8.293],

}

# 2. Convertir a DataFrame de Pandas
df_resumen = pd.DataFrame(datos_experimentos)

# 3. Mostrar la tabla sencilla en el notebook
df_resumen

,Soporte Mínimo,Hiperparámetro (min_support),Reglas Descubiertas,Lift Máximo
0,0.1%,0.001,257,13.770
1,0.2%,0.002,52,10.140
2,0.5%,0.005,19,8.293
3,1.0%,0.010,18,8.293